name: Split-save 15G image to /mnt

on:
  workflow_dispatch:

env:
  IMAGE: lianxintao/perfetto:latest

jobs:
  split-save:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize disk space
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost "$AGENT_TOOLSDIRECTORY"
          sudo docker system prune -af --volumes
          df -h

      # 1. 准备脚本（输出目录改到 /mnt）
      - name: Create split-save script
        run: |
          cat <<'EOF' > split-save.sh
          set -e
          IMAGE=$1
          WORK=/mnt/split          # ← 改到外挂 SSD
          mkdir -p $WORK
          # 获取所有层
          layers=$(docker manifest inspect $IMAGE 2>/dev/null | jq -r '.layers[].digest' | cut -d: -f2)
          [ -z "$layers" ] && { echo "fall back to local pull"; docker pull $IMAGE; exit 0; }
          i=0
          for layer in $layers; do
            echo "==> pull & save layer $i : sha256:$layer"
            docker pull $IMAGE@sha256:$layer 2>/dev/null || true
            docker save $IMAGE > $WORK/$i.tar
            docker image prune -af --filter "until=0s" -f
            i=$((i+1))
          done
          echo "==> concat all splits"
          cat $WORK/*.tar > /mnt/final.tar
          echo "final.tar ready at /mnt/final.tar"
          EOF
          chmod +x split-save.sh

      # 2. 初始 pull
      - name: Initial pull
        run: docker pull ${{ env.IMAGE }}

      # 3. 执行分片 save（输出到 /mnt）
      - name: Split save & concat
        run: ./split-save.sh ${{ env.IMAGE }}

      # 4. 上传制品（路径指向 /mnt）
      - name: Upload final tar
        uses: actions/upload-artifact@v4
        with:
          name: perfetto-15g-final
          path: /mnt/final.tar
