name: Save any image to tar with 75 GB SSD

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Docker image to pull, e.g. prom/prometheus'
        required: true
        default: 'prom/prometheus'

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      # ---------- 0. 解析镜像短名 ----------
      - name: Parse short name
        id: parse
        run: |
          # 去掉仓库域名前缀，再取冒号或斜杠后的第一段
          SHORT=$(echo "${{ github.event.inputs.image }}" | sed -E 's@^.*/@@; s/[:@].*$//')
          echo "short=$SHORT" >> $GITHUB_OUTPUT
          echo "tarball=${SHORT}-latest.tar" >> $GITHUB_OUTPUT

      # ---------- 1. 清理系统盘 ----------
      - name: Maximize disk space
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost "$AGENT_TOOLSDIRECTORY"
          sudo docker system prune -af --volumes
          df -h

      # ---------- 2. 把 Docker 目录搬到 /mnt ----------
      - name: Move Docker to /mnt
        run: |
          sudo systemctl stop docker
          sudo mv /var/lib/docker /mnt/docker
          sudo ln -s /mnt/docker /var/lib/docker
          sudo systemctl start docker

      # ---------- 3. 工作目录也放 /mnt ----------
      - name: Set WORKDIR to /mnt
        run: |
          sudo mkdir -p /mnt/work
          sudo chmod 777 /mnt/work
          echo "GITHUB_WORKSPACE=/mnt/work" >> $GITHUB_ENV

      # ---------- 4. 拉镜像 ----------
      - name: Pull image
        run: docker pull "${{ github.event.inputs.image }}"

      # ---------- 5. save ----------
      - name: Docker save
        run: |
          docker save -o /mnt/work/${{ steps.parse.outputs.tarball }} ${{ github.event.inputs.image }}

      # ---------- 6. 上传 ----------
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.parse.outputs.short }}-latest-tar
          path: /mnt/work/${{ steps.parse.outputs.tarball }}
